### ISSUE TITLE
Better error handling - Use of process.exit

### ISSUE THREAD

**Issue by jan-j** [vot/ffbinaries-node#6]
Hi, thank you very much for this and related packages. It's great and easy to use.

I have only one issue with way errors are handled, because in case there is no internet (or some other error occurres) in `listVersions` and `getVersionData` functions, `process.exit(1)` is used. It makes it impossible for gracefully handling these errors programatically. I'm creating Electron app and without using child process or somehow overriding `process.exit` method it's not possible to keep the application from exiting.

I'm happy to create PR myself if I know it's going to be merged.

**Comment by vot** [comment]
Hi, glad you found the library useful. You're absolutely right, I'll need to implement the methods correctly with callbacks returning errors where necessary.

I think there was a reason why I went with `process.exit` where a callback would be more sensible but now I can't recall what it was (some of these callbacks are still there, commented out).
I'll try to address it in the next few days (or feel free to create a PR in the meantime, I tend to merge most things straight away).

**Comment by vot** [comment]
I just pushed an update which changes the problematic calls to callbacks, error first.

I also added examples dir, it'll allow me to test the lib a little bit more efficiently in the future. Let me know if that covers your usage.

Thanks for raising this. Version 0.1.7 is already on npm, give it a go and see if it behaves as expected :)

**Comment by jan-j** [comment]
Thanks for your work! Much appreciated.

I skimmed though code changes and although it still not perfect error handling (it can fail silently, without returning error through callback), but at least it's not making my Electron app to exit. Good enough for my use case. Thanks again.

**Comment by vot** [comment]
Glad that did the trick 👍 

For now I just wanted to make sure it's not killing the applications as that's a critical bug.
I agree all callbacks need to be more consistent and always return the results, I'll try to address that soon.
